### ISSUE TITLE
Debian 9.8 - Error with install Navi

### ISSUE THREAD

**Issue by Mrnous** [gustafn/install-ns#8] opened 2019-03-27 08:38 UTC
modules/websocket/log-view.adp
modules/websocket/log-view.tcl
modules/websocket/makevars.txt
modules/websocket/websocket-procs.tcl
gcc -I/usr/include/postgresql -O2 -fomit-frame-pointer -DNDEBUG -Wall -fPIC  -pipe  -I/usr/local/ns/include -I"/usr/local/ns/include"  -DHAVE_CONFIG_H    -c -o nsdbpg.o nsdbpg.c
In file included from /usr/local/ns/include/nsthread.h:45:0,
                 from /usr/local/ns/include/ns.h:41,
                 from /usr/local/ns/include/nsdb.h:40,
                 from dbpg.h:54,
                 from nsdbpg.c:37:
/usr/local/ns/include/nsconfig.h:23:0: warning: "HAVE_CRYPT" redefined
 #define HAVE_CRYPT /**/

In file included from dbpg.h:47:0,
                 from nsdbpg.c:37:
/usr/include/postgresql/pg_config.h:122:0: note: this is the location of the previous definition
 #define HAVE_CRYPT 1

gcc -I/usr/include/postgresql -O2 -fomit-frame-pointer -DNDEBUG -Wall -fPIC  -pipe  -I/usr/local/ns/include -I"/usr/local/ns/include"  -DHAVE_CONFIG_H    -c -o tclcmds.o tclcmds.c
In file included from /usr/local/ns/include/nsthread.h:45:0,
                 from /usr/local/ns/include/ns.h:41,
                 from /usr/local/ns/include/nsdb.h:40,
                 from dbpg.h:54,
                 from tclcmds.c:37:
/usr/local/ns/include/nsconfig.h:23:0: warning: "HAVE_CRYPT" redefined
 #define HAVE_CRYPT /**/

In file included from dbpg.h:47:0,
                 from tclcmds.c:37:
/usr/include/postgresql/pg_config.h:122:0: note: this is the location of the previous definition
 #define HAVE_CRYPT 1

/bin/rm -Rf nsdbpg.so
gcc -shared -I/usr/include/postgresql -O2 -fomit-frame-pointer -DNDEBUG -Wall -fPIC  -pipe  -I/usr/local/ns/include -I"/usr/local/ns/include"  -DHAVE_CONFIG_H   -L/usr/local/ns/lib -o nsdbpg.so nsdbpg.o tclcmds.o  -L/usr/lib -Wl,-rpath,/usr/lib -lnsdb -lpq -lnsthread -lnsd -L/usr/local/ns/lib -ltcl8.6  -lgcc_s  -lieee -lm  -Wl,--export-dynamic  -L/usr/local/ns/lib -lssl -lcrypto -Wl,-rpath,:/usr/local/ns/lib
/usr/local/ns/bin/install-sh -c nsdbpg.so /usr/local/ns/bin/
------------------------ Installing Tcl Thread library -----------------------

**Comment by gustafn** [comment] 2019-03-27 08:56
The message above is a warning, not an error.

The warning is caused by the fact that two of the loaded packages use the same configure macro 
`AC_CHECK_LIB([crypt], [crypt], ...)`, namely naviserver and postgres. It is not the job of install-ns.sh to fix this. When time permits, i'll try to get rid of this annoyance in the NaviServer code base.

Did you face a real issue?

**Comment by gustafn** [comment] 2019-03-27 10:23
I've solved this issue by changing the (recommended) name of the macro HAVE_CRYPT as used by NaviServer. This will be part of the next NaviServer release. It will be only seen by install-ns automatically after the next release, or when NaviServer is configured in the script as HEAD.

**Closed by gustafn** 2019-03-27 10:23 UTC
